stages:
  - test

test:
  stage: test
  coverage: '/\d+\%$/'
  script:
    - sudo apt-get install unixodbc-dev
    - source ~/.venv/bspump/bin/activate
    - python setup.py install
    - pip install -r requirements-dev.txt
    - coverage run -m unittest
    - coverage report -m
