stages:
  - test

test:
  image: python:3.7
  stage: test
  coverage: '/\d+\%$/'
  script:
    - python setup.py install
    - pip install -r requirements-dev.txt
    - pip install --upgrade git+git://github.com/TeskaLabs/asab.git#egg=asab
    - pip install flake8
    - coverage run -m unittest
    - coverage report -m
    - flake8 bspump
