language: python

python:
  - "3.6"
  - "3.7"

install:
  - python setup.py install
  - pip install https://downloads.tableau.com/tssoftware/Tableau-SDK-Python-Linux-64Bit-10-3-23.tar.gz
  - pip install pyarrow>=0.13.0
  - pip install -r requirements-dev.txt
  - pip install codecov

script:
  - coverage run -m unittest
  - coverage report

after_success:
  - codecov
